/*
 *   Copyright (C) 2026 GeorgH93
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package at.pcgamingfreaks.Database;

import org.intellij.lang.annotations.Language;
import org.junit.Before;
import org.junit.Test;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * Tests for {@link SQLiteTableValidator}.
 * <p>
 * The tests use minimal dynamic proxies for the JDBC {@link Connection}, {@link PreparedStatement}, {@link ResultSet}
 * and {@link Statement} interfaces (like {@link SQLTableValidatorTest}), so they do not require Mockito and also run
 * on Java 16+ where mocking {@code java.sql.Connection} is not possible.
 * <p>
 * They verify the SQLite specific {@code sqlite_master} lookup, the {@code ALTER TABLE ... ADD COLUMN} statements
 * generated by {@link SQLiteTableValidator#addColumn(Connection, String, String, String)} and that all operations
 * that are not implemented for SQLite execute no SQL at all.
 */
public class SQLiteTableValidatorTest
{
	private static final String SQLITE_MASTER_QUERY = "SELECT sql FROM sqlite_master WHERE tbl_name=?;";

	private SQLiteTableValidator validator;
	private Connection connection;
	private List<String> executedStatements;
	private List<String> preparedStatements;
	private List<String> boundParameters;
	private int executeQueryCalls;
	private boolean tableExists;
	private String currentCreateStatement;

	@Before
	public void setUp()
	{
		validator = new SQLiteTableValidator();
		executedStatements = new ArrayList<>();
		preparedStatements = new ArrayList<>();
		boundParameters = new ArrayList<>();
		executeQueryCalls = 0;
		tableExists = true;
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");

		final Statement statement = (Statement) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Statement.class}, (proxy, method, args) -> {
			if("executeUpdate".equals(method.getName()) && args != null && args.length == 1)
			{
				executedStatements.add((String) args[0]);
			}
			return defaultValue(method.getReturnType());
		});
		final ResultSet resultSet = (ResultSet) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{ResultSet.class}, (proxy, method, args) -> {
			switch(method.getName())
			{
				case "next":
					return tableExists;
				case "getString":
					return (args != null && args.length == 1 && "sql".equals(args[0])) ? currentCreateStatement : null;
				default:
					return defaultValue(method.getReturnType());
			}
		});
		final PreparedStatement preparedStatement = (PreparedStatement) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{PreparedStatement.class}, (proxy, method, args) -> {
			switch(method.getName())
			{
				case "setString":
					boundParameters.add(args[0] + "=" + args[1]);
					return null;
				case "executeQuery":
					executeQueryCalls++;
					return resultSet;
				default:
					return defaultValue(method.getReturnType());
			}
		});
		connection = (Connection) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Connection.class}, (proxy, method, args) -> {
			switch(method.getName())
			{
				case "createStatement":
					return statement;
				case "prepareStatement":
					preparedStatements.add((String) args[0]);
					return preparedStatement;
				default:
					return defaultValue(method.getReturnType());
			}
		});
	}

	//region getCurrentCreateStatement tests
	@Test
	public void testGetCurrentCreateStatementReadsFromSqliteMaster() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL", "`val` TEXT");
		assertEquals(currentCreateStatement, validator.getCurrentCreateStatement(connection, "test"));
		assertEquals(Arrays.asList(SQLITE_MASTER_QUERY), preparedStatements);
		assertEquals(Arrays.asList("1=test"), boundParameters);
		assertEquals(1, executeQueryCalls);
	}

	@Test
	public void testGetCurrentCreateStatementReturnsEmptyStringForMissingTable() throws SQLException
	{
		tableExists = false;
		assertEquals("", validator.getCurrentCreateStatement(connection, "test"));
		assertEquals(Arrays.asList(SQLITE_MASTER_QUERY), preparedStatements);
		assertEquals(Arrays.asList("1=test"), boundParameters);
		assertEquals(1, executeQueryCalls);
	}
	//endregion

	//region validate - table creation and input validation tests
	@Test
	public void testValidateCreatesTableWhenNotExisting() throws SQLException
	{
		tableExists = false;
		@Language("SQL") final String definition = tableDefinition("`id` INTEGER NOT NULL", "PRIMARY KEY (`id`)");
		validator.validate(connection, definition);
		assertEquals(Arrays.asList(definition), executedStatements);
	}

	@Test
	public void testValidateThrowsOnInvalidDefinition()
	{
		assertValidateRejected("");
		assertValidateRejected("DROP TABLE `test`;");
	}
	//endregion

	//region validate - no-op tests
	@Test
	public void testValidateNoChangesOnMatchingLayout() throws SQLException
	{
		@Language("SQL") final String[] columns = {"`id` INTEGER NOT NULL", "`val` TEXT NOT NULL DEFAULT 'x'", "PRIMARY KEY (`id`)", "UNIQUE INDEX `idx` (`val`)"};
		currentCreateStatement = tableDefinition(columns);
		validator.validate(connection, tableDefinition(columns));
		assertTrue(executedStatements.isEmpty());
	}
	//endregion

	//region validate - column tests
	@Test
	public void testValidateAddsColumn() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "`val` VARCHAR(255) NOT NULL DEFAULT 'x'"));
		assertEquals(Arrays.asList("ALTER TABLE `test` ADD COLUMN `val` VARCHAR(255) NOT NULL DEFAULT 'x'"), executedStatements);
	}

	@Test
	public void testValidateAddsColumnWithPlainColumnName() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "val VARCHAR(255)"));
		assertEquals(Arrays.asList("ALTER TABLE `test` ADD COLUMN `val` VARCHAR(255)"), executedStatements);
	}

	@Test
	public void testValidateAddsMultipleColumnsInOrder() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "`val` VARCHAR(255)", "`data` BLOB"));
		assertEquals(Arrays.asList("ALTER TABLE `test` ADD COLUMN `val` VARCHAR(255)", "ALTER TABLE `test` ADD COLUMN `data` BLOB"), executedStatements);
	}

	@Test
	public void testValidateDoesNotModifyColumnFlags() throws SQLException
	{
		// SQLite does not support modifying columns, the operation is a no-op that must not execute any SQL
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL AUTO_INCREMENT"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotModifyColumnType() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INT NOT NULL");
		validator.validate(connection, tableDefinition("`id` BIGINT NOT NULL"));
		assertTrue(executedStatements.isEmpty());
	}
	//endregion

	//region validate - unimplemented operation tests
	@Test
	public void testValidateDoesNotAddPrimaryKey() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "PRIMARY KEY (`id`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotModifyPrimaryKey() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL", "`val` INTEGER NOT NULL", "PRIMARY KEY (`id`)");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "`val` INTEGER NOT NULL", "PRIMARY KEY (`id`, `val`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotAddIndex() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "INDEX `idx` (`id`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotModifyIndex() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL", "INDEX `idx` (`id`)");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "INDEX `idx` (`id`, `val`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotAddUniqueIndex() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "UNIQUE INDEX `idx` (`id`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotMakeIndexUnique() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL", "UNIQUE INDEX `idx` (`id`)");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "UNIQUE KEY `idx` (`id`, `val`)"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotAddForeignKey() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "CONSTRAINT `fk` FOREIGN KEY (`id`) REFERENCES `table2` (`id`) ON DELETE CASCADE"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testValidateDoesNotModifyForeignKey() throws SQLException
	{
		currentCreateStatement = tableDefinition("`id` INTEGER NOT NULL", "CONSTRAINT `fk` FOREIGN KEY (`id`) REFERENCES `table2` (`id`)");
		validator.validate(connection, tableDefinition("`id` INTEGER NOT NULL", "CONSTRAINT `fk` FOREIGN KEY (`id`) REFERENCES `table2` (`id`) ON DELETE CASCADE"));
		assertTrue(executedStatements.isEmpty());
	}

	@Test
	public void testUnimplementedOperationsExecuteNoSql() throws SQLException
	{
		// Direct invocations of all not implemented operations: they are no-ops and must neither throw nor execute any SQL
		validator.modifyColumn(connection, "test", "id", "INT NOT NULL");
		validator.addIndex(connection, "test", "idx", "(`id`)");
		validator.modifyIndex(connection, "test", "idx", "(`id`)");
		validator.makeIndexUnique(connection, "test", "idx", "(`id`)");
		validator.addUniqueIndex(connection, "test", "idx", "(`id`)");
		validator.addConstraint(connection, "test", "fk", "(`id`)", "`table2` (`id`)");
		validator.modifyConstraint(connection, "test", "fk", "(`id`)", "`table2` (`id`)");
		validator.addPrimaryKey(connection, "test", "(`id`)");
		validator.modifyPrimaryKey(connection, "test", "(`id`)");
		assertTrue(executedStatements.isEmpty());
	}
	//endregion

	//region test helpers
	private void assertValidateRejected(@Language("SQL") final String definition)
	{
		try
		{
			validator.validate(connection, definition);
			throw new AssertionError("Expected an IllegalArgumentException to be thrown for: " + definition);
		}
		catch(IllegalArgumentException ignored)
		{
		}
		catch(SQLException e)
		{
			throw new AssertionError("Expected an IllegalArgumentException to be thrown for: " + definition, e);
		}
	}

	private static String tableDefinition(final String... columns)
	{
		final StringBuilder builder = new StringBuilder("CREATE TABLE `test` (\n");
		for(int i = 0; i < columns.length; i++)
		{
			builder.append("  ").append(columns[i]);
			if(i < columns.length - 1) builder.append(',');
			builder.append('\n');
		}
		return builder.append(')').toString();
	}

	private static Object defaultValue(final Class<?> type)
	{
		if(!type.isPrimitive() || type == void.class) return null;
		if(type == boolean.class) return false;
		if(type == long.class) return 0L;
		if(type == float.class) return 0F;
		if(type == double.class) return 0D;
		if(type == byte.class) return (byte) 0;
		if(type == short.class) return (short) 0;
		if(type == char.class) return '\0';
		return 0;
	}
	//endregion
}
